apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: fontend
    app: ngingx
spec:
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx:1.12
  replicas: 3
  selector:
    matchLabels:
      app: myapp